-
  name:  'Backend Service'
  uriPattern: 'neosidekick/n8n/{@controller}/{@action}'
  defaults:
    '@package':    'NEOSidekick.ContentRepositoryWebhooks'
    '@format':     'json'
  httpMethods: ['GET', 'POST']
