-
  name:  'Tools Service'
  uriPattern: 'neosidekick/lawnmower/tools/{@action}'
  defaults:
    '@package':    'NEOSidekick.Lawnmower'
    '@controller': 'Tools'
    '@format':     'json'
  httpMethods: ['GET', 'POST']
