NEOSidekick:
    Lawnmower:
        endpoints:
            workspacePublished:
                - 'https://neosidekick.app.n8n.cloud/webhook-test/neos-workspace-published'
Neos:
    Flow:
        mvc:
            routes:
                NEOSidekick.Lawnmower: true
        security:
            authentication:
                providers:
                    'NEOSidekick.Lawnmower:Token':
                        provider: Flownative\TokenAuthentication\Security\HashTokenProvider
                        requestPatterns:
                            'NEOSidekick.Lawnmower:BackendControllers':
                                pattern: ControllerObjectName
                                patternOptions:
                                    controllerObjectNamePattern: 'NEOSidekick\Lawnmower\Controller\.*'
