NEOSidekick:
  ContentRepositoryWebhooks:
    endpoints:
      # nodeUpdated:
      #  - 'https://neosidekick.app.n8n.cloud/webhook-test/neos-content-change'
      # nodeAdded:
      #   - 'https://neosidekick.app.n8n.cloud/webhook-test/neos-content-change'
      # nodeRemoved:
      #   - 'https://neosidekick.app.n8n.cloud/webhook-test/neos-content-change'
      # nodePropertyChanged:
      #   - 'https://neosidekick.app.n8n.cloud/webhook-test/neos-content-change'
      # nodePublished:
      #   - 'https://neosidekick.app.n8n.cloud/webhook-test/neos-content-change'
      # nodeDiscarded:
      #   - 'https://neosidekick.app.n8n.cloud/webhook-test/neos-content-change'
      workspacePublished:
        - 'https://neosidekick.app.n8n.cloud/webhook-test/neos-workspace-published'

Neos:
  Flow:
    mvc:
      routes:
        'NEOSidekick.ContentRepositoryWebhooks': true
    security:
      authentication:
        providers:
          'NEOSidekick.ContentRepositoryWebhooks:Token':
            provider: Flownative\TokenAuthentication\Security\HashTokenProvider
            requestPatterns:
              'NEOSidekick.ContentRepositoryWebhooks:BackendControllers':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'NEOSidekick\ContentRepositoryWebhooks\Controller\.*'
